# Generated by Django 4.2.4 on 2023-09-04 18:39

import ckeditor.fields
import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', core.fields.AutoSlugField(populate_from='name', unique=True, verbose_name='Слаг')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('accredited', models.BooleanField(default=False, verbose_name='Аккредитованное учебное заведение')),
                ('epc', models.FloatField(default=0, verbose_name='Средний заработок с перехода')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Псевдоним школы',
                'verbose_name_plural': 'Псевдонимы школ',
            },
        ),
    ]
