# Generated by Django 4.2.4 on 2023-08-02 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('accredited', models.BooleanField(default=False, verbose_name='Аккредитованное учебное заведение')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('epc', models.FloatField(default=0, verbose_name='Средний заработок с перехода')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('disabled', models.BooleanField(default=False, verbose_name='Отключен')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='schools.school', verbose_name='Школа')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.datasource', verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Псевдоним школы',
                'verbose_name_plural': 'Псевдонимы школ',
                'unique_together': {('school', 'source')},
            },
        ),
    ]
