# Generated by Django 4.2.4 on 2023-08-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='SchoolTagOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='schools.schooltag', verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Вариант метки',
                'verbose_name_plural': 'Варианты меток',
            },
        ),
        migrations.CreateModel(
            name='SchoolTagMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reviews.review', verbose_name='Отзыв')),
                ('tag_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schooltagoption', verbose_name='Вариант метки')),
            ],
            options={
                'verbose_name': 'Совпадение метки',
                'verbose_name_plural': 'Совпадения меток',
            },
        ),
    ]
