# Generated by Django 4.2.4 on 2023-09-04 18:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на отзыв')),
                ('published', models.DateField(verbose_name='Дата публикации отзыва')),
                ('rating', models.IntegerField(choices=[(0, 'Нет рейтинга'), (1, 'Одна звезда'), (2, 'Две звезды'), (3, 'Три звезды'), (4, 'Четыре звезды'), (5, 'Пять звёзд')], default=0, verbose_name='Рейтинг')),
                ('advantages', models.TextField(blank=True, null=True, verbose_name='Положительная часть отзыва')),
                ('disadvantages', models.TextField(blank=True, null=True, verbose_name='Отрицательная часть отзыва')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Основной текст отзыва')),
                ('text_sentiment', models.IntegerField(choices=[(1, 'Неизвестен'), (2, 'Негативный'), (3, 'Нейтральный'), (4, 'Позитивный')], default=1, verbose_name='Тональность текста отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Источник отзыва')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Источник отзывов',
                'verbose_name_plural': 'Источники отзывов',
            },
        ),
        migrations.CreateModel(
            name='ReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
            options={
                'db_table': 'review_criterion',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='criteria',
            field=models.ManyToManyField(through='reviews.ReviewCriterion', to='reviews.criterion', verbose_name='Критерии оценки'),
        ),
        migrations.AddField(
            model_name='review',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewsource', verbose_name='Источник отзыва'),
        ),
        migrations.CreateModel(
            name='CriterionVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='reviews.criterion', verbose_name='Критерий оценки')),
            ],
            options={
                'verbose_name': 'Вариация критерия оценки',
                'verbose_name_plural': 'Вариации критериев оценки',
            },
        ),
    ]
