# Generated by Django 4.2.4 on 2023-09-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name': 'Критерий оценки', 'verbose_name_plural': 'Критерии оценки'},
        ),
        migrations.RenameField(
            model_name='reviewcriterion',
            old_name='category',
            new_name='criterion',
        ),
    ]
